import logging
import subprocess
import sys
import os
import time
from datetime import datetime

# Configure Logging
LOG_FILE = "agent.log"
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.FileHandler(LOG_FILE),
        logging.StreamHandler(sys.stdout)
    ]
)
logger = logging.getLogger("AgentManager")

def run_script(script_name, args=[]):
    """
    Runs a python script as a subprocess and streams output.
    """
    logger.info(f"🚀 Starting {script_name}...")
    start_time = time.time()
    
    cmd = [sys.executable, script_name] + args
    try:
        # Run and capture output
        result = subprocess.run(
            cmd, 
            capture_output=True, 
            text=True, 
            check=False # We handle return codes manually
        )
        
        # Log stdout/stderr
        if result.stdout:
            for line in result.stdout.splitlines():
                logger.info(f"[{script_name}] {line}")
        
        if result.stderr:
            for line in result.stderr.splitlines():
                logger.warning(f"[{script_name}] stderr: {line}")
        
        duration = time.time() - start_time
        
        if result.returncode == 0:
            logger.info(f"✅ {script_name} finished successfully in {duration:.2f}s.")
            return True
        else:
            logger.error(f"❌ {script_name} failed with exit code {result.returncode}.")
            return False

    except Exception as e:
        logger.error(f"❌ critical error running {script_name}: {e}")
        return False

def main():
    logger.info("=== 🕵️ Agent Manager Started ===")
    
    # 1. Publish Posts
    # We pass 'sites_data.json' if it exists, or let it fetch from sheet
    # Assuming standard behavior: python publish_post.py
    logger.info("--- Phase 1: Publishing ---")
    if not run_script("publish_post.py"):
        logger.error("🛑 Aborting workflow due to publishing failure.")
        return

    # 2. Visual Verification
    # We run this against the results.json generated by publish_post.py
    logger.info("--- Phase 2: Verification ---")
    if os.path.exists("results.json"):
        run_script("visual_verifier.py", ["results.json"])
    else:
        logger.warning("⚠️ results.json not found. Skipping verification.")

    # 3. Analytics & Reporting
    logger.info("--- Phase 3: Analytics ---")
    run_script("analytics.py")
    
    logger.info("=== ✅ Workflow Completed ===")

if __name__ == "__main__":
    main()
