name: Unicorn Pro CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./unicorn-pro-api
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: './unicorn-pro-api/package-lock.json'
      - run: npm ci
      - run: npx prisma generate
      - run: npm test

  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./unicorn-pro-mvp
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: './unicorn-pro-mvp/package-lock.json'
      - run: npm ci
      - run: npm run test
      - run: npm run build
